### ISSUE TITLE
[EPIC] Foundation model serving

### ISSUE THREAD

**Issue by Shreyanand** [redhat-et/foundation-models-for-documentation#37]
Serving foundation models on an OpenShift cluster is a crucial step for using them in production. As a part of this issue we will deploy demo models using open source tools and/or the stack recommended by RHODS. Following questions would be further explored as a part of this epic:

- [ ] How can we create model endpoints using Modelmesh on the cluster? This should involve instructions on deploying modelmesh using Operator Hub and adding the model to a s3 bucket. Create the predict function and explain how it is being called and demo a notebook that sends a payload to the model endpoint. 

- [ ] What is the resource requirement of the deployed model? Explain the resources defined for the model pod. What is the throughput of the model? How can we increase the throughput? Given a combination of hardware, model type, and optimization techniques, what can be the maximum expected and observed throughput?

- [ ] Explore [text-generation-webui](https://github.com/oobabooga/text-generation-webui/tree/main). How flexible is it for different models? Would we need a custom server.py for some models?
